### ISSUE TITLE
Feature: Newline control character should be modifiable when saving CSV

### ISSUE THREAD

**Issue by m0nk3y2k4** [JeP42/robotframework-easycsvmap#1]
Currently easycsvmap will not specify a newline control character when saving CSVs to a file. This results in opencsv-lib to use its default newline control character `LF` (escape \n) what may lead to issues e.g. on Windows-based systems as they often expect an additional carriage return: `CR LF` (escape \r\n).

It would be great if easycsvmap would respect/keep the newline control characters from the parsed CSV or at least provide some mechanism to set a specific newline character to be used when saving the CSV. Otherwise the outbound CSV may be unusable for consuming instances.

Best regards,
Daniel

**Comment by JeP42** [comment]
Lib now provides capability to specify custom newline sequence via last parameter of the keyword `Parse Csv From File`. Backslashes have to be escaped, e.g. like this: 

`Parse Csv From File | 4711 | {TEMPDIR}/download.csv | 0 | ; | " | \\r\\n`

**Comment by m0nk3y2k4** [comment]
Works like a charm :)
Thanks a lot!
