### ISSUE TITLE
Feature: Add support for Byte Order Marks (BOM) in CSV files

### ISSUE THREAD

**Issue by m0nk3y2k4** [JeP42/robotframework-easycsvmap#2]
It seems the underlying [OpenCSV](https://search.maven.org/artifact/net.sf.opencsv/opencsv/2.3/jar) implementation is not capable of handling BOM's at the very beginning of CSV files properly. Instead of recognizing the BOM and consider it as an encoding information, the BOM will be assumed to be part of the regular CSV content. This can lead to problems when the parsed CSV is saved again in regards of quoting the single CSV values.

**What's working:**
> CSV input file **without** BOM: `Value1;Value2;Value3`

When the file is parsed, changed and saved again, the single values will be quoted.

> CSV output file **without** BOM: `"Value1";"Value2";"Value3"`

**What's broken:**
> CSV input file **with** BOM at the very beginning: `[BOM]Value1;Value2;Value3`

When the file is parsed, changed and saved again, the single values will be quoted. However, as there is no special handling for BOM's, the BOM bytes will be considered to be part of Value1 and thus will be included in the quotes.

> CSV output file **with** BOM as part of the first value: `"[BOM]Value1";"Value2";"Value3"`

In this state the output file is kind of currpted for post-processing. If the file is parsed again (e.g. by some other software) the BOM will no longer be recognized (even if the software supports proper BOM handling) as it's not at the very beginning but inside the quote of the first value.

Note: I know quoting can be disabled but it's enabled by default and this would not be a proper "solution" :)

**To be:**
There are different options (e.g. simply ignore the BOM while parsing a file) but I guess the best way would be to handle the BOM like "_Input = Output_". So if the input file does not contain a BOM there should also be no BOM in the output file (easycsvmap should not "add" a BOM by itself). On the other hand: if the input file contains a BOM it should be stored in the session but removed from the actual CSV data. When the CSV is saved again, the stored BOM should be added to the very beginning of the output stream followed by the actual, quoted CSV content. For example:

> Input: `[BOM]Value1;Value2;Value3`
> Output: `[BOM]"Value1";"Value2";"Value3"`

I've already implemented this solution by using an [BOMInputStream](https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/input/BOMInputStream.html). So if you're willing to grant me permissions to push topic branches to this repository I'd create a pull request containing my implementation :)

Regards,
Daniel

**Comment by JeP42** [comment]
Hi Daniel,
as you've already mentioned, OpenCSV is used for reading and writing the csv files. If you think there is a bug in this library I would suggest to report the bug for OpenCSV and then and upgrade to version which includes the bugfix.
Have you already checked with latest version of OpenCSV? 

regards,
Jens

**Comment by m0nk3y2k4** [comment]
Hi Jens,

> Have you already checked with latest version of OpenCSV?

It seems you already use the latest _net.sf.opencsv_ implementation. However, it's from 2011 and there are multiple other _opencsv_ artifacts with different group IDs which seem to be newer. I'll checkout if one of these artifacts is to be considered as an actual successor (with new/changed group ID) or if these are some kind of forks or even completely different implementations. I'll keep you updated.

Regards,
Daniel

**Comment by JeP42** [comment]
ok, however, if you have a solution for this a pull request would be appreciated. I've just pushed test cases which can be used to reproduce the issue...

**Comment by m0nk3y2k4** [comment]
Hi Jens,
I included your tests into my fix. I also had to set the surefire encoding to UTF-8. Otherwise the tests failed when building from Windows command line (although the tests passed properly when executed from within eclipse).

However, it seems I'm unable to push a new topic/feature branch to the repo:
`git-receive-pack not permitted on 'https://github.com/JeP42/robotframwork-easycsvmap.git/'`

As this is my first push to a github repo I'm uncertain if I'm acting a bit clumsy or if it's some repository permission setting that prevents me from pushing changes.

Best regards,
Daniel

**Comment by JeP42** [comment]
Hi Daniel,

the usual way to contribute is via pull requests. I would recommend that you fork the original repo, create a topic branch, push your changes to the topic branch and create a pull request. More details on how to create a pull request from a fork: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

Best regards
Jens





Am 10. März 2019 12:53:11 MEZ schrieb m0nk3y2k4 <notifications@github.com>:
>Hi Jens,
>I included your tests into my fix. I also had to set the surefire
>encoding to UTF-8. Otherwise the tests failed when building from
>Windows command line (although the tests passed properly when executed
>from within eclipse).
>
>However, it seems I'm unable to push a new topic/feature branch to the
>repo:
>`git-receive-pack not permitted on
>'https://github.com/JeP42/robotframwork-easycsvmap.git/'`
>
>As this is my first push to a github repo I'm uncertain if I'm acting a
>bit clumsy or if it's some repository permission setting that prevents
>me from pushing changes.
>
>Best regards,
>Daniel
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/JeP42/robotframework-easycsvmap/issues/2#issuecomment-471281134

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by m0nk3y2k4** [comment]
Hi Jens,

ah, I see. I used a different tutorial in which the change was directly pushed to a new topic branch inside the actual repository (and then create a pull request based on this branch). I'll try to fork the repo first, push a topic branch to the fork and finally create a pull request based on this branch. Thanks for the info!

Regards,
Daniel

**Comment by JeP42** [comment]
merged pull request
