### ISSUE TITLE
Bug: Resource leak in FileUtil

### ISSUE THREAD

**Issue by m0nk3y2k4** [JeP42/robotframework-easycsvmap#4]
The FileUtil.java uses an internal BOM input stream to read the CSV file and initialize the object:

_From FileUtil#initialize_
`BOMInputStream input = new BOMInputStream(Files.newInputStream(Paths.get(this.filePath)));`

Unfortunately the input stream is not closed after the object has been initialized. So the library keeps an open stream to the underlying CSV file. This could result in being unable to delete the CSV file as long as the remote library is running.

**Comment by JeP42** [comment]
fixed with pull request #5
